### PR TITLE
Restructuring

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
This pull request is only a proposal for turning the repository upside-down. Please [take a look to the new structure](https://github.com/helpfulengineering/devops/tree/restructuring) and accept only those changes that look reasonable enough to you.

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
@imonthercks, I don't know yet the real scope of the `guidance` documentation.
Could the Auth0 document be part of the [architecture](https://github.com/helpfulengineering/devops/tree/restructuring/documentation/architecture) directory instead? It nearly seems mature enough to be an architecture item on its own.

**Comment by 0x2b3bfa0** [comment]
The main `REDME.md` keeps duplicating some of the file contents in the `documentation` directory.

I think that this approach has some consistency issues, but it's great to offer an overview of the repository documentation, as linking every resource would require an extra click to get any useful information.

**Comment by imonthercks** [comment]
@0x2b3bfa0, I would be fine with moving the authentication and authorization page right under documentation if that would work.

**Comment by 0x2b3bfa0** [comment]
> @0x2b3bfa0, I would be fine with moving the authentication and authorization page right under documentation if that would work. 

@imonthercks If we can't assign it to any other category, that would be an option. What do you think about my proposal of moving it to `documentation/guidance`?

**Review by dmangot — APPROVED** [review]

**Pull request merged**
